# Generated by Django 3.0.6 on 2020-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin', models.CharField(choices=[('gluttony', 'Gluttony'), ('lust', 'Lust'), ('greed', 'Greed'), ('pride', 'Pride'), ('sloth', 'Sloth'), ('wrath', 'Wrath'), ('envy', 'Envy')], max_length=8)),
                ('quote', models.TextField()),
            ],
        ),
    ]
