# Generated by Django 3.0.6 on 2020-05-20 17:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinquote',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2020, 5, 20, 17, 30, 27, 416678)),
            preserve_default=False,
        ),
    ]
