# Generated by Django 3.0.6 on 2020-05-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_sinquote_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinquote',
            name='date_created',
        ),
    ]
